/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lobi.college.mis.components;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lobi.college.mis.util.Database;
import lobi.college.mis.util.Util;
import javax.swing.JScrollPane;
import lobi.college.mis.util.StudentInfo;

/**
 *
 * @author shady
 */
public class RegisteredStudents extends javax.swing.JPanel {

    private String User, Dept;
    private final Color Silver;
    Toolkit toolkit;
    Dimension dimension;

    /**
     * Creates new form RegisteredStudents
     *
     * @param user
     * @param dept
     */
    public RegisteredStudents(String user, String dept) {
        this.User = user;
        this.Dept = dept;
        Silver = new Color(247, 247, 247);
        toolkit = Toolkit.getDefaultToolkit();
        dimension = toolkit.getScreenSize();
        initComponents();
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new JScrollPane(tblStudents, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED)
        ;
        tblStudents = new javax.swing.JTable();

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lobi/college/mis/resources/gfx/research.png"))); // NOI18N
        jButton1.setText("<html><b>Search</b>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setForeground(new java.awt.Color(31, 28, 28));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setDoubleBuffered(true);
        jScrollPane3.setWheelScrollingEnabled(false);

        /*tblStudents.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table,
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
                Component c = super.getTableCellRendererComponent(table,
                    value, isSelected, hasFocus, row, column);
                c.setBackground(row%2==0 ? Color.white : Silver);
                return c;
            };
        });
        tblStudents.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);*/
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Birth Certificate", "Student Name", "National ID No / Passport No", "Gender", "Nationality", "County", "Sub County", "Mobile  Phone", "Email Address", "Postal Address", "Gender", "Next of Kin", "Next of Kin Phone"
            }
        ));
        /*
        tblStudents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        */
        tblStudents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblStudents.setDoubleBuffered(true);
        tblStudents.setPreferredScrollableViewportSize(new Dimension(dimension.width,dimension.height));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(User + Dept);        // TODO add your handling code here:
        Util util = new Util();

        populateTable(util.formatString(txtSearch.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        Util util = new Util();
        populateTable(util.formatString(txtSearch.getText()));        // TODO add your handling code here:  

    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        String x = model.getValueAt(tblStudents.getSelectedRow(), 0).toString();
       // JOptionPane.showMessageDialog(this, x);
        try {
            StudentInfo studentInfo = new StudentInfo(x);
            studentInfo.setLocationRelativeTo(this);
            studentInfo.setVisible(true);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_tblStudentsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        try {

            // create a sql date object so we can use it in our INSERT statement
           // File f = new File("server.properties");
            Connection cnn = Database.getConnection();

            PreparedStatement ps = cnn.prepareStatement("Select * from Students");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) tblStudents.getModel();
            tm.setRowCount(0);

            while (rs.next()) {

                Object o[] = {rs.getString("StudentID"), rs.getInt("B_Certificate"), rs.getString("Student_Name"), rs.getInt("IDNo"), rs.getString("Gender"), rs.getString("Nationality"), rs.getString("County"), rs.getString("Subcounty"), rs.getString("Phone"), rs.getString("email"), rs.getString("Address"), rs.getString("Gender"), rs.getString("NextOfKin"), rs.getString("NextofKinPhone")};
                tm.addRow(o);

            }

            tblStudents.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
    }

    private void populateTable(String key) {

        try {

            // create a sql date object so we can use it in our INSERT statement
            Connection cnn = Database.getConnection();
            PreparedStatement ps = cnn.prepareStatement("SELECT * FROM Students WHERE StudentID like '%" + key + "%' OR Student_Name like '%" + key + "%' OR B_Certificate like '%" + key + "%' OR IDNo like '%" + key + "%' OR Gender like '%" + key + "%' OR Nationality like '%" + key + "%' OR County like '%" + key + "%' OR Subcounty like '%" + key + "%' OR Division like '%" + key + "%' OR Location like '%" + key + "%' OR SubLocation like '%" + key + "%' OR Village like '%" + key + "%' OR Address like '%" + key + "%' OR Phone like '%" + key + "%' OR email like '%" + key + "%' OR NextOfKin like '%" + key + "%' OR NextofKinPhone like '%" + key + "%' OR NextofKinEmail");
            //PreparedStatement ps = cnn.prepareStatement("Select * from Students where "+dbParam+" like '%"+key+"%'");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) tblStudents.getModel();
            tm.setRowCount(0);

            while (rs.next()) {

                Object o[] = {rs.getString("StudentID"), rs.getInt("B_Certificate"), rs.getString("Student_Name"), rs.getInt("IDNo"), rs.getString("Gender"), rs.getString("Nationality"), rs.getString("County"), rs.getString("Subcounty"), rs.getString("Phone"), rs.getString("email"), rs.getString("Address"), rs.getString("Gender"), rs.getString("NextOfKin"), rs.getString("NextofKinPhone")};
                tm.addRow(o);

            }

            tblStudents.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
        }
    }
}
