/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lobi.college.mis;

import java.awt.BorderLayout;
import lobi.college.mis.components.ClassManager;
import lobi.college.mis.components.DepartmentalRequisition;
import lobi.college.mis.components.Exams;

/**
 *
 * @author shady
 */
public class AcademicPane extends javax.swing.JInternalFrame {
private String User,Dept;
    /**
     * Creates new form AcademicPane
     */
    public AcademicPane(String user,String dept) {
        this.User=user;
        this.Dept=dept;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnClassMgt = new javax.swing.JButton();
        btnExams = new javax.swing.JButton();
        btnRequisition = new javax.swing.JButton();
        AcadPane = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Academic Pane");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/lobi/college/mis/resources/gfx/progress.png"))); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnClassMgt.setText("Class Management");
        btnClassMgt.setFocusable(false);
        btnClassMgt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClassMgt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClassMgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassMgtActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClassMgt);

        btnExams.setText("Examination");
        btnExams.setFocusable(false);
        btnExams.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExams.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExams);

        btnRequisition.setText("Requisition and Inventory");
        btnRequisition.setFocusable(false);
        btnRequisition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRequisition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRequisition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequisitionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRequisition);

        javax.swing.GroupLayout AcadPaneLayout = new javax.swing.GroupLayout(AcadPane);
        AcadPane.setLayout(AcadPaneLayout);
        AcadPaneLayout.setHorizontalGroup(
            AcadPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AcadPaneLayout.setVerticalGroup(
            AcadPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AcadPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(AcadPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamsActionPerformed
        // TODO add your handling code here:
        Exams exams = new Exams(User,Dept);
        AcadPane.removeAll();
        AcadPane.setVisible(false);
        AcadPane.setSize(AcadPane.getSize().width, AcadPane.getSize().height);
        AcadPane.setVisible(true);
        AcadPane.setLayout(new BorderLayout());
        AcadPane.add(exams);
        AcadPane.setVisible(true);
        pack();


    }//GEN-LAST:event_btnExamsActionPerformed

    private void btnClassMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassMgtActionPerformed
        // TODO add your handling code here:
        ClassManager classmgr = new ClassManager(User,Dept);
        AcadPane.removeAll();
        AcadPane.setVisible(false);
        AcadPane.setSize(AcadPane.getSize().width, AcadPane.getSize().height);
        AcadPane.setVisible(true);
        AcadPane.setLayout(new BorderLayout());
        AcadPane.add(classmgr);
        AcadPane.setVisible(true);
        pack();
    }//GEN-LAST:event_btnClassMgtActionPerformed

    private void btnRequisitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequisitionActionPerformed
        // TODO add your handling code here:
         DepartmentalRequisition dptR = new DepartmentalRequisition(User,Dept);
        AcadPane.removeAll();
        AcadPane.setVisible(false);
        AcadPane.setSize(AcadPane.getSize().width, AcadPane.getSize().height);
        AcadPane.setVisible(true);
        AcadPane.setLayout(new BorderLayout());
        AcadPane.add(dptR);
        AcadPane.setVisible(true);
        pack();
    }//GEN-LAST:event_btnRequisitionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AcadPane;
    private javax.swing.JButton btnClassMgt;
    private javax.swing.JButton btnExams;
    private javax.swing.JButton btnRequisition;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
